Repository jupyterhub/configurable-http-proxy, pull requests merged in 2021-04, with the labels that each got.

#304 Build and publish Docker Hub image for amd64 and arm64
  .github/workflows/npm-publish.yml
  .github/workflows/publish.yml
Labels: enhancement

#305 Changelog for 4.3.2
  CHANGELOG.md
Labels: documentation

#307 ci: github actions security
  .github/workflows/publish.yml
Labels: ci
