Repository jupyterhub/configurable-http-proxy, pull requests merged in 2022-08, with the labels that each got.

#416 Updated alpine base image to 3.16
  Dockerfile
Labels: maintenance

#417 Add changelog for 4.5.2
  CHANGELOG.md
Labels: documentation

#418 ci: add dependabot bumping of github actions
  .github/dependabot.yml
Labels: ci
