Repository jupyterhub/configurable-http-proxy, pull requests merged in 2022-02, with the labels that each got.

#369 fix custom-header
  bin/configurable-http-proxy
  test/cli_spec.js
Labels: bug

#371 image: use latest alpine (3.12 -> 3.15)
  .github/workflows/publish.yml
  Dockerfile
Labels: dependencies

#372 ci: test against node 17, rely on pre-commit.ci, tweak workflow triggers and comments
  .github/workflows/publish.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: ci

#373 Add changelog for 4.5.1
  CHANGELOG.md
Labels: documentation
